name: .NET Framework Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: KongZhiKa.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # 安装 NuGet 工具
    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: latest

    # 添加 MSBuild 到环境变量
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    # 使用 nuget restore 还原依赖项
    - name: Restore NuGet packages
      run: nuget restore ${{ env.Solution_Name }}

    # 构建整个解决方案
    - name: Build solution
      run: msbuild ${{ env.Solution_Name }} /p:Configuration=${{ matrix.configuration }}

    # 如果你有测试项目，可以取消注释以下部分
    # - name: Run tests
    #   run: dotnet test YourTestProject\YourTestProject.csproj --no-build --verbosity normal
